package com.unipar.rinhaRatos.enums

enum class Habilidades {
    LEPTOSPIROSE, NUVEMDELAMA, FEDORCORROSIVO,
    AUTOCURADO, ANTISSEPTICO, ESCUDOANTIGENO,
    MUTACAOAGUDA, SOROEXPERIMENTAL, DURATESTON,
    MORDIDADESACO, CASCAVELDEPALHA, SARACOTEIARURAL,
    DADOVICIADO, TRAPACECIRO, ALLIN,
    MENTEDEARQUIVO, PAGINASCORTANTES, MAPADASFALHAS
}