package com.unipar.rinhaRatos.enums

enum class RatoStatus {
    CREATED,
    USER_NOT_FOUND,
    USER_ALREADY_HAS_3_RATOS,
    NON_EXISTENT_CLASS_OR_HABILIDADE,
    RATO_NOT_FOUND,
    USER_DONT_HAS_THIS_RATO,
    NO_CONTENT,
    BATALHA_NOT_FOUND,
    BATALHA_FULL,
    OK,
    BATALHA_ALREADY_STARTED,
    RATO_NOT_ELIGIBLE,
    BAD_REQUEST
}